### ISSUE TITLE
Handle removed resources  

### ISSUE THREAD

**Issue by outscale-mdr** [outscale/terraform-provider-outscale#287] opened 2023-02-01 08:49 UTC
Hello team,

I've created resources with terraform then I've removed them from another tools (ok that's bad).
It seems that the plugin does not handle removed resources.

<img width="1002" alt="Capture d’écran 2023-02-01 à 09 39 08" src="https://user-images.githubusercontent.com/91073311/215994870-a919bcb3-0a01-4372-ba4b-83c2af7dfa4e.png">

Is this something the plugin could handle, the recreation  of removed resources ?

**Comment by outscale-toa** [comment] 2023-02-01 09:45
Hi @outscale-mdr,
Thanks for reaching us, we are looking at your issue.
Can you please add a terraform configuration file?

Best regards,

**Comment by outscale-mdr** [comment] 2023-02-01 09:48
Just use [this example](https://github.com/outscale/terraform-provider-outscale/tree/master/examples/net_vm) and for external deletion, just go to cockpit and tear down the Net

**Comment by FredericBerot-Armand** [comment] 2023-02-03 15:21
Hi @outscale-mdr,

Which version of the plugin are you using? Because I can't reproduce the bug with the latest.
I thing this issue was resolved with the PR #267.

**Closed** 2023-02-10 11:00 UTC
Labels: bug
